"""Autogenerate

Revision ID: 7ef058ae4f77
Revises: e0219246eb2c
Create Date: 2025-05-12 00:02:56.126594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef058ae4f77'
down_revision: Union[str, None] = 'e0219246eb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision', sa.Column('text', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision', 'text')
    # ### end Alembic commands ###
